# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoDJ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoDJ
pod 'SnapKit', '~> 4.0.0'
pod 'MGSwipeTableCell'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.6'
pod 'TextFieldEffects'

end
